title: Писанина
subtitle: думки вголос

baseurl: ""

footer_only_homepage: true
footer_url: "https://pysanyna.com"
footer_text: "Дякую!"

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Про мене"
   link: "about"
